apiVersion: v1
kind: Pod
metadata:
  name: architect
  labels:
    ci: architect-build
spec:
  containers:
   - name: architect-build
     image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/openanalytics/architect-build
     securityContext:
      privileged: true  
     tty: true
