apiVersion: v1
kind: Pod
metadata:
  name: architect
  labels:
    ci: architect-build
spec:
  securityContext:
    fsGroup: 65534
  containers:
  - name: maven
    image: maven:3.8-eclipse-temurin-17
    resources:
      requests: 
        memory: "4Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"
    volumeMounts:
    - name: workspace-volume
      subPath: .root/.m2/repository
      mountPath: /root/.m2/repository
    - name: workspace-volume
      subPath: .root/tmp
      mountPath: /tmp
    securityContext:
      privileged: true
    command:
    - cat
    tty: true
