apiVersion: v1
kind: Pod
metadata:
  name: architect
  labels:
    ci: architect-build
spec:
  securityContext:
    fsGroup: 65534
  containers:
  - name: jnlp
    securityContext:
      privileged: true
  - name: maven
    image: library/maven:3.9-eclipse-temurin-21
    imagePullPolicy: Always
    resources:
      requests:
        memory: "4Gi"
        cpu: "1500m"
      limits:
        memory: "4Gi"
        cpu: "2000m"
    volumeMounts:
    - name: workspace-volume
      subPath: .root/.m2/repository
      mountPath: /root/.m2/repository
    - name: workspace-volume
      subPath: .root/tmp
      mountPath: /tmp
    securityContext:
      privileged: true
    command:
    - cat
    tty: true
